language: node_js
node_js:
- "8"
- "10"

before_install:
# required for `canvas` npm package
- sudo apt-get install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++

install:
- npm -g install npm
- npm install

script:
- npm run test:ci
- npm run build

notifications:
    email: false

cache:
    directories:
    - node_modules
